name: Sincronizar Repositório

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync-repository:
    runs-on: ubuntu-latest
    steps:
      - name: Executar espelhamento do repositório
        env:
          CGU_SYNC_TOKEN_CGUACTIONS: ${{ secrets.CGU_SYNC_TOKEN_CGUACTIONS }}
          CGU_SYNC_TOKEN_CGUGOVBR: ${{ secrets.CGU_SYNC_TOKEN_CGUGOVBR }}
        run: |
          set -e

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Clona o repo cgu-se-dti/mod-sei-eouv como mirror
          git clone --mirror https://x-access-token:${CGU_SYNC_TOKEN_CGUACTIONS}@github.com/cgu-se-dti/mod-sei-eouv.git cgu-se-dti-mirror
          cd cgu-se-dti-mirror

          # Faz push para o repo cgugovbr/mod-sei-eouv
          git remote add cgugovbr https://x-access-token:${CGU_SYNC_TOKEN_CGUGOVBR}@github.com/cgugovbr/mod-sei-eouv.git
          git push cgugovbr refs/heads/main:refs/heads/main
          git push cgugovbr --tags
